spring:
  application:
    name: nacos-discovery-consumer-feign

  cloud:
    nacos:
      discovery:
        server-addr: 47.111.114.208:8848
        username: nacos
        password: nacos

server.port: 9080