spring:
  application:
    name: nacos-discovery-gateway-server

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
      routes:
        - id: nacos-discovery-provider
          uri: lb://nacos-discovery-provider
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1

server:
  port: 9700