spring:
  application:
    name: nacos-discovery-consumer-webflux

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

server:
  port: 9070