server:
  port: 8020

spring:
  application:
    name: seata-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order?serverTimezone=GMT%2B8&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: Taylor
    password: Taylor_123
    driver-class-name: com.mysql.cj.jdbc.Driver